all:
	cd action && go build -x .
	cd alignment && go build -x .
	cd builder && go build -x .
	cd clipboard && go build -x .
	cd demo && go build -x .
	cd spinbutton && go build -x .
	cd toolbar && go build -x .
	cd dnd && go build -x .
	cd drawable && go build -x .
	cd event && go build -x .
	cd expander && go build -x .
	cd iconview && go build -x .
	cd listview && go build -x .
	cd locale && go build -x .
	cd notebook && go build -x .
	cd number && go build -x .
	cd sourceview && go build -x .
	cd statusicon && go build -x .
	cd table && go build -x .
	cd thread && go build -x .
	cd treeview && go build -x .
	cd twitter && go build -x .
	cd twitterstream && go get && go build -x .
