all:
	cd demo && gomake
	cd twitter && gomake
	cd listview && gomake
	cd treeview && gomake
	cd notebook && gomake
	cd thread && gomake
	cd table && gomake
	cd expander && gomake
	cd drawable && gomake
	cd builder && gomake
	cd sourceview && gomake

clean:
	cd demo && gomake clean
	cd twitter && gomake clean
	cd listview && gomake clean
	cd treeview && gomake clean
	cd notebook && gomake clean
	cd thread && gomake clean
