// +build !cgocheck

package gtkgl

const (
	ATTR_NONE             = 0
	ATTR_USE_GL           = 1
	ATTR_BUFFER_SIZE      = 2
	ATTR_LEVEL            = 3
	ATTR_RGBA             = 4
	ATTR_DOUBLEBUFFER     = 5
	ATTR_STEREO           = 6
	ATTR_AUX_BUFFERS      = 7
	ATTR_RED_SIZE         = 8
	ATTR_GREEN_SIZE       = 9
	ATTR_BLUE_SIZE        = 10
	ATTR_ALPGHA_SIZE      = 11
	ATTR_DEPTH_SIZE       = 12
	ATTR_STENCIL_SIZE     = 13
	ATTR_ACCUM_RED_SIZE   = 14
	ATTR_ACCUM_GREEN_SIZE = 15
	ATTR_ACCUM_BLUE_SIZE  = 16
	ATTR_ACCUM_ALPHA_SIZE = 17
)

const (
	ATTR_X_VISUAL_TYPE_EXT           = 0x22
	ATTR_TRANSPARENT_TYPE_EXT        = 0x23
	ATTR_TRANSPARENT_INDEX_VALUE_EXT = 0x24
	ATTR_TRANSPARENT_RED_VALUE_EXT   = 0x25
	ATTR_TRANSPARENT_GREEN_VALUE_EXT = 0x26
	ATTR_TRANSPARENT_BLUE_VALUE_EXT  = 0x27
	ATTR_TRANSPARENT_ALPHA_VALUE_EXT = 0x28
)
